apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-check 
  namespace: default
spec:
  project: production
  source:
    path: helm
    repoURL: https://github.com/dancchen/argocd-15-min.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
